local:
  ip: 127.0.0.1
  port: 8080
name: springboot
app:
  name: this is ${name}
ds:
  hosts[0]: localhost
  hosts[1]: 127.0.0.1
  hosts[2]: 192.168.1.1
  ports[0]: 8080
  ports[1]: 8081
  ports[2]: 8082
spring:
  profiles:
    active: dev,test
